import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Logo } from "@/components/Logo";
import { ProgressBar } from "@/components/ProgressBar";
import { QuestionCard } from "@/components/QuestionCard";
import { Button } from "@/components/ui/button";
import { ArrowRight, ArrowLeft, Clock, Brain } from "lucide-react";
import { toast } from "sonner";

// Sample questions - In production, these would be generated by AI
const sampleQuestions: Record<string, { question: string; options: string[] }[]> = {
  hr: [
    { question: "What is the primary purpose of conducting a job analysis?", options: ["To determine employee salaries", "To define job responsibilities and requirements", "To evaluate employee performance", "To plan company events"] },
    { question: "Which recruitment method is most effective for senior positions?", options: ["Social media advertising", "Employee referrals", "Executive search firms", "Job boards"] },
    { question: "What does HRIS stand for?", options: ["Human Resource Information System", "Human Relations Internal Service", "Hiring Resource Integration Software", "Human Resource Implementation Strategy"] },
    { question: "What is the purpose of an exit interview?", options: ["To negotiate salary", "To gather feedback about employee experience", "To finalize termination paperwork", "To discuss promotion opportunities"] },
    { question: "Which law protects employees from workplace discrimination?", options: ["OSHA", "Title VII of the Civil Rights Act", "FLSA", "ERISA"] },
  ],
  frontend: [
    { question: "What is the Virtual DOM in React?", options: ["A browser API", "A lightweight copy of the real DOM", "A CSS framework", "A testing library"] },
    { question: "Which CSS property is used for flexible box layout?", options: ["grid", "float", "flexbox", "display: flex"] },
    { question: "What is the purpose of React hooks?", options: ["To style components", "To manage state and lifecycle in functional components", "To create APIs", "To optimize images"] },
    { question: "What does 'responsive design' primarily focus on?", options: ["Fast loading times", "Adapting to different screen sizes", "Database optimization", "Security features"] },
    { question: "Which tool is used for JavaScript bundling?", options: ["Node.js", "Webpack", "MongoDB", "Express"] },
  ],
  backend: [
    { question: "What is REST in API design?", options: ["A testing framework", "A database type", "An architectural style for APIs", "A programming language"] },
    { question: "What does ORM stand for?", options: ["Object-Relational Mapping", "Online Resource Manager", "Optimized Runtime Module", "Object Request Model"] },
    { question: "Which database type is MongoDB?", options: ["Relational", "Graph", "Document-based NoSQL", "Key-value store"] },
    { question: "What is the purpose of middleware in Express.js?", options: ["To style the frontend", "To process requests before reaching route handlers", "To manage the database", "To compile JavaScript"] },
    { question: "What is Docker used for?", options: ["Frontend development", "Containerization of applications", "Email services", "Payment processing"] },
  ],
  default: [
    { question: "What is the most important skill for professional success?", options: ["Technical expertise only", "Communication and collaboration", "Working in isolation", "Avoiding feedback"] },
    { question: "How do you handle tight deadlines?", options: ["Panic and rush through tasks", "Prioritize tasks and communicate proactively", "Ignore the deadline", "Blame others for delays"] },
    { question: "What is your approach to learning new skills?", options: ["Wait for formal training only", "Proactive self-learning and practice", "Avoid new technologies", "Only learn when forced to"] },
    { question: "How do you handle constructive criticism?", options: ["Take it personally", "Use it as an opportunity to improve", "Ignore it completely", "Argue against it"] },
    { question: "What defines a good team player?", options: ["Working alone", "Supporting colleagues and sharing knowledge", "Taking all the credit", "Avoiding team meetings"] },
  ],
};

const Assessment = () => {
  const navigate = useNavigate();
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [answers, setAnswers] = useState<(number | null)[]>([]);
  const [timeLeft, setTimeLeft] = useState(1800); // 30 minutes
  const [isLoading, setIsLoading] = useState(true);
  const [questions, setQuestions] = useState<{ question: string; options: string[] }[]>([]);

  useEffect(() => {
    // Get selected domain and load questions
    const domainData = localStorage.getItem("selectedDomain");
    if (!domainData) {
      navigate("/domain-selection");
      return;
    }

    const domain = JSON.parse(domainData);
    const domainQuestions = sampleQuestions[domain.id] || sampleQuestions.default;
    setQuestions(domainQuestions);
    setAnswers(new Array(domainQuestions.length).fill(null));
    
    // Simulate AI loading
    setTimeout(() => setIsLoading(false), 1500);
  }, [navigate]);

  useEffect(() => {
    // Timer countdown
    const timer = setInterval(() => {
      setTimeLeft(prev => {
        if (prev <= 0) {
          clearInterval(timer);
          handleSubmit();
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(timer);
  }, []);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  };

  const handleAnswerSelect = (optionIndex: number) => {
    const newAnswers = [...answers];
    newAnswers[currentQuestion] = optionIndex;
    setAnswers(newAnswers);
  };

  const handleNext = () => {
    if (currentQuestion < questions.length - 1) {
      setCurrentQuestion(currentQuestion + 1);
    }
  };

  const handlePrevious = () => {
    if (currentQuestion > 0) {
      setCurrentQuestion(currentQuestion - 1);
    }
  };

  const handleSubmit = () => {
    const unanswered = answers.filter(a => a === null).length;
    if (unanswered > 0) {
      toast.warning(`You have ${unanswered} unanswered questions`);
    }
    
    // Store answers and navigate to completion
    localStorage.setItem("assessmentAnswers", JSON.stringify(answers));
    navigate("/completion");
  };

  if (isLoading) {
    return (
      <div className="min-h-screen gradient-hero flex items-center justify-center">
        <div className="text-center animate-fade-in">
          <div className="w-20 h-20 gradient-primary rounded-2xl flex items-center justify-center mx-auto mb-6 animate-pulse-ring">
            <Brain className="text-primary-foreground" size={40} />
          </div>
          <h2 className="text-2xl font-display font-bold text-foreground mb-2">
            Preparing Your Assessment
          </h2>
          <p className="text-muted-foreground">
            AI is generating personalized questions...
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen gradient-hero">
      {/* Header */}
      <header className="p-6 flex justify-between items-center border-b border-border/50 bg-card/50 backdrop-blur-sm sticky top-0 z-10">
        <Logo size="sm" />
        <div className="flex items-center gap-2 px-4 py-2 bg-card rounded-lg shadow-card">
          <Clock className={`${timeLeft < 300 ? 'text-destructive' : 'text-primary'}`} size={18} />
          <span className={`font-mono font-bold ${timeLeft < 300 ? 'text-destructive' : 'text-foreground'}`}>
            {formatTime(timeLeft)}
          </span>
        </div>
      </header>

      {/* Main Content */}
      <main className="container max-w-3xl py-8 px-6">
        <div className="mb-8">
          <ProgressBar current={currentQuestion + 1} total={questions.length} />
        </div>

        {questions[currentQuestion] && (
          <QuestionCard
            question={questions[currentQuestion].question}
            options={questions[currentQuestion].options}
            selectedOption={answers[currentQuestion]}
            onSelect={handleAnswerSelect}
          />
        )}

        <div className="flex justify-between items-center mt-8">
          <Button 
            variant="outline" 
            onClick={handlePrevious}
            disabled={currentQuestion === 0}
          >
            <ArrowLeft size={18} />
            Previous
          </Button>

          {currentQuestion < questions.length - 1 ? (
            <Button 
              variant="gradient" 
              onClick={handleNext}
              disabled={answers[currentQuestion] === null}
            >
              Next Question
              <ArrowRight size={18} />
            </Button>
          ) : (
            <Button 
              variant="success" 
              onClick={handleSubmit}
            >
              Submit Assessment
              <ArrowRight size={18} />
            </Button>
          )}
        </div>

        {/* Question Navigation */}
        <div className="mt-10 p-4 bg-card rounded-xl shadow-card">
          <p className="text-sm font-medium text-muted-foreground mb-3">Quick Navigation</p>
          <div className="flex flex-wrap gap-2">
            {questions.map((_, index) => (
              <button
                key={index}
                onClick={() => setCurrentQuestion(index)}
                className={`w-10 h-10 rounded-lg font-medium text-sm transition-all duration-200 ${
                  currentQuestion === index
                    ? 'gradient-primary text-primary-foreground shadow-soft'
                    : answers[index] !== null
                    ? 'bg-accent/20 text-accent border border-accent/30'
                    : 'bg-secondary text-muted-foreground hover:bg-secondary/80'
                }`}
              >
                {index + 1}
              </button>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Assessment;
